VERSION = "2.2.2"

RETRY_DELAY = 15 # Delay in seconds before retrying a failed request. (default, can be modified in config.ini)
RETRY_MAX = 30 # Number of failed tries (includes the first try) after which SAC will stop trying and quit. (default, can be modified in config.ini)

HIGH_DLC_WARNING = 125

EXTS_TO_REPLACE = (".txt", ".ini", ".cfg")

CONFIG = "config.ini"
AUTOUPDATER_EXE = "steam_auto_cracker_gui_autoupdater.exe"
OPCREDIT = "BigBoiCJ"
GITHUB_RAWHOST = "raw.githubusercontent.com"
GITHUB_APIHOST = "api.github.com"
GITHUB_ACCREPOSTR = "BigBoiCJ/SteamAutoCracker"
GITHUB_ALLRELEASESJSON = f"https://{GITHUB_APIHOST}/repos/{GITHUB_ACCREPOSTR}/releases"
GITHUB_LATESTRELEASESJSON = f"{GITHUB_ALLRELEASESJSON}/latest"
GITHUB_LATESTVERSIONJSON = f"https://{GITHUB_RAWHOST}/{GITHUB_ACCREPOSTR}/autoupdater/latestversion.json"
GITHUB_AUTOUPDATER = f"https://{GITHUB_RAWHOST}/{GITHUB_ACCREPOSTR}/autoupdater/{AUTOUPDATER_EXE}"



##

TITLE_MAIN = f"SteamAutoCracker GUI v{VERSION}"
TITLE_SETTINGS = f"{TITLE_MAIN} - Settings"
TITLE_UPDATE = f"{TITLE_MAIN} - Update"


LBL_TITLESETTINGS = "Settings"
LBL_TITLEUPDATE = "Update"
LBL_THEME = "Theme:"
LBL_UPDATES = "Updates:"
LBL_UPDATESDESC = "This will search the latest version on GitHub. If you're afraid of leaking your IP to GitHub, use a VPN and/or disable auto updating."
LBL_STEAMLESS = "Steamless:"
LBL_STEAMLESSDESC = "This will allow SAC to bypass the SteamStub DRM if it is used."
LBL_ADVANCED = "Advanced:"
LBL_ADVANCEDDESC = "Advanced settings, don't modify unless you know what you're doing."
LBL_CRACKMETHOD = "Crack approach:"
LBL_FILENAMES = "File names:"
LBL_FILENAMESDESC = "You can enter the name the different files will have.\nIt is recommended to keep the default ones."
LBL_APIDLLBAK = "steam_api.dll backup:"
LBL_API64DLLBAK = "steam_api64.dll backup:"
LBL_EXESUFFIXBAK = "Game EXE backup suffix:"
LBL_OTHERSUFFIXBAK = "Other files backup suffix:"
LBL_RETRYDELAY = "RetryDelay:"
LBL_RETRYMAX = "RetryMax:"
LBL_SELECTFOLDER = "Select where your game is installed :"
LBL_SELECTEDFOLDER = "Selected folder:\n{path}"
LBL_SELECTEDFOLDER_LOG = "\nSelected folder: {path}"
LBL_SEARCHINGAPPLIST = "Searching in the App List..."
LBL_DLAPPLIST = "The App List isn't downloaded on your computer, downloading it..."
LBL_APPNOTFOUND = "App not found!"
LBL_UPDATINGAPPLIST = "Updating the App List..."
LBL_REQERROR = "An error has occurred"
LBL_APPIDNOTFOUND = "AppID {id} not found."
LBL_APPIDNOTGAME = "AppID {id} is not a game."
LBL_APPIDNOTGAMEBYPASS = "AppID {id} is not a game. You can bypass this verification in the Advanced settings."
LBL_UPDATEDAPPLIST = "App List updated!"
LBL_GETTINGSTEAMGAMEINFO = "[1/2] Retrieving game informations from Steam..."
LBL_GETTINGSTEAMGAMEDLC = "[2/2] Retrieving DLCs..."
LBL_DLCREQFAILED = "Retrieve DLC request failed!"
LBL_NOGAMEDLC = "- No DLC found for this game!"
LBL_FOUNDDLC = "Found DLC"
LBL_OLDRETRIEVEOPT = "Using the old retrieve option (RetrieveDLCOption is set to 1)"
LBL_GAMEHIGHDLC = f"WARNING: This game has more than {HIGH_DLC_WARNING} DLCs. Requests may fail due to Steam rate limiting. If it does, just give it time, it'll eventually manage to retrieve all DLCs."
LBL_NOAPPNAMEFORDLC = "Error! No App Name found for AppID {id}"
LBL_FETCHEDDETAILSFORGAME = "Finished retrieving all the details about the game {name} (appID: {id})"
LBL_FETCHEDDETAILSFORGAME_S = "All details retrieved for {name}!"
LBL_GAMECRACKENTRY = "Enter the Name or AppID of the game you want to Crack:"
LBL_CRACKLIST = "Crack List"
LBL_SELECTEDCRACK = "Selected crack:"
LBL_UPDATEAVAILCONFIRM = "A new update for Steam Auto Cracker GUI is available.\nDo you want to download it automatically?"
LBL_VERSIONCUR = f"Current version: {VERSION}"
LBL_VERSIONNEW = "Latest version: {version}"
LBL_SEARCHINGUPDATE = "Searching for updates..."
LBL_UPTODATE = "SAC is up to date!"
LBL_OUTDATED = "SAC is outdated!"
LBL_DLUPDATERPLSWAIT = "Downloading the autoupdater, please wait...\nThis might take some time depending on your internet connection speed..."
LBL_UDATEERROR = "An error occurred. The autoupdater (steam_auto_cracker_gui_autoupdater.exe) already exists.\nSAC couldn't delete the autoupdater. Please try to remove it yourself, or try again."
LBL_UPDATERSAVING = "Writing the autoupdater, please wait..."
LBL_UPDATERINSTALLED = "Autoupdater installed!\nStarting it in 3 seconds..."

BTN_SELECTFOLDER = "Select a folder"
BTN_UPDATECHECK = "Check for updates"
BTN_RESETSETTINGS = "Reset to default"
BTN_RESETCRACK = "Reset to default"
BTN_SAVE = "Save"
BTN_SEARCH = "Search"
BTN_UDPATEAPPLIST = "Update the App List"
BTN_NONE = "NONE"
BTN_CRACKGAME = "Crack the game"
BTN_UPDATE = "Update now"
BTN_COPYRELURL = "Copy the release URL"
BTN_DONTUPDATE = "Don't update yet"

CHKBOX_BYPASSGAMEVERIF = "Bypass the game verification\n(allows to crack AppIDs not recognized as games)"

RADIOBTN_UPDATECHECKNO = "Don't automatically check\n(RECOMMENDED FOR PRIVACY)"
RADIOBTN_UPDATECHECKAUTO = "Automatically check when SAC starts\n(RECOMMENDED FOR CONVENIENCE)"
RADIOBTN_CRACKAUTO = "Crack the game automatically\n(RECOMMENDED)"
RADIOBTN_CRACKCONFIGDLLGAMEDIR = "Only create the crack config, and put it in the same directory as steam_api(64).dll"
RADIOBTN_CRACKCONFIGDLLTOOLDIR = "Only create the crack config, and put it in the same directory as the Steam Auto Cracker tool\n(currently bugged, doesn't work!)"
RADIOBTN_STEAMLESSNO = "Don't attempt to use Steamless"
RADIOBTN_STEAMLESSYES = "Attempt to use Steamless (RECOMMENDED)"